# Generated by Django 4.2.18 on 2025-02-27 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("socialnetwork", "0003_comment"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserFollower",
        ),
    ]
